language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
before_install:
  - gem install bundler
before_script:
  - bundle exec rake appraisal:setup
script:
  - bundle exec rake appraisal test
