language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
before_install:
  - gem install bundler
before_script:
  - bundle install
  - bundle exec rake appraisal:install
script:
  - bundle exec rake appraisal test
