language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - gemfiles/rails3.0.x.gemfile
  - gemfiles/rails3.1.x.gemfile
  - gemfiles/rails3.2.x.gemfile
  - gemfiles/rails4.0.x.gemfile
